export { default as Login } from './Login/Login'
export { default as NotFound } from './NotFound/NotFound'
export { default as Profile } from './Profile/Profile'
export { default as Dialogs } from './Dialogs/Dialogs'
export { default as Users } from './Users/Users'
export { default as Chat } from './Chat/Chat'
